name: Fetch GitHub Contributions

on:
  workflow_dispatch: # Manually triggered, or change to schedule for periodic runs
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC (optional)

jobs:
  fetch-contributions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Contributions Data
        env:
          GITHUB_PAT: ${{ secrets.TOKEN }}
        run: |
          curl -X POST -H "Authorization: bearer $TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "query": "query { user(login: \"bruno-gehlen\") { contributionsCollection { contributionCalendar { totalContributions weeks { contributionDays { date contributionCount color } } } } } }"
          }' https://api.github.com/graphql > contributions.json

      - name: Commit and Push Contributions Data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add contributions.json
          git commit -m "Update contributions data"
          git push
